@startuml
autonumber
participant consumer
participant broker

group 第一部分
consumer -> consumer : 封装pull请求
consumer -> broker : pull请求
end
group 第二部分
broker -> broker : 查找消息
broker --> consumer : 返回消息
end
group 第三部分
consumer -> consumer : 处理返回的消息
end
@enduml

@startuml
autonumber
participant DefaultMQPushConsumerImpl

@enduml