@startuml

box NamesrvStartup类
participant main方法
participant createNamesrvController方法
end box


autonumber
main方法 -> main方法 : 调用 main方法(args) 启动
group 创建 namesrv
main方法 -> createNamesrvController方法 : 调用 this#createNamesrvController(args)
createNamesrvController方法 -> createNamesrvController方法 :
end
group 启动 namesrv
main方法 -> main方法 : 调用 this#start() 方法
end
@enduml