@startuml
!theme vibrant

|Master|
start
:启动;
:向namesrv注册;
:启动Slave监听线程;
stop

|Slave|
start
:启动;
:向namesrv注册;
:获取master路由信息;
:与master建立连接;
|Master|
:处理Slave连接请求;
:创建HAConnect;
|Slave|
:连接成功;
if (本地是否有commitlog文件) then (没有)
    :向master获取最新的commitlog offset;
    |Master|
    :获取commitlog offset;
    |Slave|
    :基于offset创建commitlog文件;
else (有)
    :获取本地的commitlog offset;
endif
@enduml