@startuml
autonumber

client -> mq : half  msg
group store half msg

end
client -> client : perform other operations
opt
client -> mq : submit
mq -> topic_subscriber
else
client -> mq : rollback
end


@enduml