@startuml
autonumber

Consumer -> Broker ++: pull

group 步骤1:获取锁
Broker -> Broker : 获取topic&group锁
note right of Broker
锁的粒度为 topic + group
1. topic一样，group不一样，不存在锁竞争
2. group一样，topic不一样，不存在锁竞争
end note

end

group 步骤2:进行消费
Broker -> Broker : 获取消息
Broker -> Broker : 消费 offset++
end

group 步骤3：释放锁
Broker -> Broker : 释放锁
end

Broker --> Consumer --: msg

@enduml