@startuml
'https://plantuml.com/component-diagram

node producer{
    rectangle 获取topic路由信息
    rectangle 选择消费队列
    rectangle 发送
}

获取topic路由信息 -> nameserver : 1
获取topic路由信息 --> 选择消费队列 : 2
选择消费队列 --> 发送 :3

node consumer {

}

node nameserver {
}

node broker {
    rectangle 存储消息
    rectangle push消息
}
发送 --> 存储消息
存储消息 --> push消息
push消息 -> consumer

@enduml